# Generated by Django 3.2.7 on 2021-09-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linktree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='owner',
            field=models.CharField(choices=[('IMOBILIARIA', 'Imobiliaria'), ('CONSTRUTORA', 'Construtora')], default='', max_length=50),
        ),
    ]
